insert into public.products (
  id,
  name,
  brand,
  category,
  status,
  image_url,
  reason,
  tags,
  signals
) values
(
  'ember-mug',
  'Temperature Control Smart Mug',
  'Ember-style pick',
  'Kitchen',
  'featured',
  'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80',
  'A polished daily-use gift for someone who nurses coffee or tea through a busy morning.',
  '{"mom":0.8,"dad":0.7,"girlfriend":0.7,"boyfriend":0.7,"coworker":0.5,"family":0.8,"partner":0.7,"close-friend":0.7,"casual":0.5,"professional":0.4,"adult":0.9,"senior":0.6,"flexible":0.8,"soon":0.6,"birthday":0.8,"christmas":0.9,"thank-you":0.6,"coffee":1,"tech":0.7,"practical":0.8,"premium":0.7,"expensive-feel":0.5}'::jsonb,
  '{"clicks":168,"saves":42,"recommendations":620,"freshness":0.84}'::jsonb
),
(
  'weighted-blanket',
  'Cotton Weighted Blanket',
  'Calm Home',
  'Wellness',
  'active',
  'https://images.unsplash.com/photo-1616627562048-896782f7a1a2?auto=format&fit=crop&w=900&q=80',
  'A comforting choice when you want the gift to feel thoughtful without being overly personal.',
  '{"mom":0.9,"dad":0.4,"girlfriend":0.8,"boyfriend":0.5,"friend":0.6,"family":0.7,"partner":0.8,"close-friend":0.7,"casual":0.3,"adult":0.8,"senior":0.7,"flexible":0.8,"birthday":0.7,"christmas":0.8,"anniversary":0.5,"wellness":1,"home":0.8,"cozy":1,"practical":0.6,"too-personal":0.45}'::jsonb,
  '{"clicks":122,"saves":51,"recommendations":510,"freshness":0.76}'::jsonb
),
(
  'pour-over-kit',
  'Pour-Over Coffee Starter Kit',
  'Brew Desk',
  'Coffee',
  'featured',
  'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=900&q=80',
  'Specific enough to feel chosen, but safe for many relationships and budgets.',
  '{"dad":0.8,"mom":0.7,"boyfriend":0.7,"girlfriend":0.6,"coworker":0.7,"friend":0.8,"family":0.8,"partner":0.6,"close-friend":0.8,"casual":0.7,"professional":0.7,"adult":0.9,"senior":0.6,"flexible":0.9,"soon":0.8,"last-minute":0.6,"birthday":0.7,"christmas":0.8,"housewarming":0.8,"thank-you":0.7,"coffee":1,"home":0.5,"practical":0.8}'::jsonb,
  '{"clicks":210,"saves":36,"recommendations":690,"freshness":0.9}'::jsonb
),
(
  'digital-frame',
  'Wi-Fi Digital Photo Frame',
  'FamilyLoop',
  'Tech',
  'featured',
  'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
  'Great for parents or family members because it turns shared memories into a living gift.',
  '{"mom":1,"dad":0.9,"girlfriend":0.4,"boyfriend":0.4,"family":1,"partner":0.4,"close-friend":0.4,"adult":0.7,"senior":0.9,"flexible":0.8,"birthday":0.8,"christmas":0.9,"anniversary":0.6,"tech":0.7,"home":0.8,"personalized":0.8,"premium":0.5,"too-personal":0.4}'::jsonb,
  '{"clicks":188,"saves":65,"recommendations":560,"freshness":0.82}'::jsonb
),
(
  'chef-knife',
  'Japanese-Style Chef Knife',
  'Mise Craft',
  'Cooking',
  'active',
  'https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=900&q=80',
  'A strong pick for someone who already enjoys cooking and appreciates durable tools.',
  '{"mom":0.6,"dad":0.8,"boyfriend":0.7,"girlfriend":0.5,"friend":0.5,"family":0.7,"partner":0.6,"close-friend":0.5,"casual":0.2,"adult":0.9,"flexible":0.8,"birthday":0.7,"christmas":0.7,"housewarming":0.8,"cooking":1,"practical":0.9,"premium":0.6}'::jsonb,
  '{"clicks":86,"saves":24,"recommendations":300,"freshness":0.63}'::jsonb
),
(
  'book-light',
  'Rechargeable Reading Light',
  'PageGlow',
  'Reading',
  'active',
  'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=900&q=80',
  'A low-risk gift that works well for coworkers, readers, and small thank-you moments.',
  '{"mom":0.7,"dad":0.6,"girlfriend":0.6,"boyfriend":0.5,"coworker":0.8,"friend":0.7,"teacher":0.9,"teen":0.7,"family":0.6,"partner":0.4,"close-friend":0.7,"casual":0.8,"professional":0.9,"adult":0.8,"senior":0.8,"flexible":0.9,"soon":0.9,"last-minute":0.8,"birthday":0.6,"christmas":0.7,"thank-you":0.8,"reading":1,"practical":0.8}'::jsonb,
  '{"clicks":74,"saves":18,"recommendations":430,"freshness":0.71}'::jsonb
),
(
  'desk-plant-kit',
  'Indoor Herb Growing Kit',
  'Green Counter',
  'Home',
  'featured',
  'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=900&q=80',
  'Cheerful, useful, and easy to place in a kitchen, office, or new home.',
  '{"mom":0.8,"dad":0.6,"girlfriend":0.7,"boyfriend":0.4,"coworker":0.8,"friend":0.7,"teacher":0.7,"family":0.7,"partner":0.5,"close-friend":0.7,"casual":0.8,"professional":0.8,"adult":0.8,"senior":0.6,"flexible":0.8,"soon":0.7,"birthday":0.7,"housewarming":1,"christmas":0.5,"thank-you":0.8,"home":1,"cooking":0.5,"practical":0.6,"fun":0.5,"decor":0.35}'::jsonb,
  '{"clicks":134,"saves":33,"recommendations":490,"freshness":0.8}'::jsonb
),
(
  'travel-tumbler',
  'Insulated Travel Tumbler',
  'DayCarry',
  'Everyday',
  'active',
  'https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=900&q=80',
  'A dependable everyday upgrade that stays appropriate even when the relationship is professional.',
  '{"mom":0.7,"dad":0.7,"girlfriend":0.6,"boyfriend":0.6,"coworker":0.9,"friend":0.8,"teacher":0.8,"teen":0.6,"family":0.7,"partner":0.5,"close-friend":0.8,"casual":0.9,"professional":0.9,"adult":0.9,"senior":0.6,"flexible":1,"soon":0.9,"last-minute":0.8,"birthday":0.6,"christmas":0.7,"thank-you":0.8,"coffee":0.7,"outdoors":0.5,"practical":1,"style":0.4}'::jsonb,
  '{"clicks":156,"saves":21,"recommendations":710,"freshness":0.78}'::jsonb
),
(
  'silk-pillowcase',
  'Silk Pillowcase Set',
  'Luma Rest',
  'Wellness',
  'active',
  'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=900&q=80',
  'Feels indulgent while staying useful, especially for someone who likes beauty or sleep upgrades.',
  '{"mom":0.7,"girlfriend":0.9,"friend":0.6,"family":0.6,"partner":0.9,"close-friend":0.7,"casual":0.2,"adult":0.9,"flexible":0.8,"birthday":0.8,"anniversary":0.7,"christmas":0.7,"wellness":0.8,"style":0.8,"cozy":0.7,"premium":0.5,"too-personal":0.55,"size-risk":0.2}'::jsonb,
  '{"clicks":97,"saves":39,"recommendations":340,"freshness":0.72}'::jsonb
)
on conflict (id) do update set
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  status = excluded.status,
  image_url = excluded.image_url,
  reason = excluded.reason,
  tags = excluded.tags,
  signals = excluded.signals,
  updated_at = now();

insert into public.merchant_offers (
  id,
  product_id,
  merchant,
  marketplace,
  external_product_id,
  price,
  currency,
  availability,
  affiliate_url,
  commission_rate,
  last_synced_at
) values
(
  'offer-ember-mug-amazon',
  'ember-mug',
  'Amazon',
  'US',
  '',
  99,
  'USD',
  'in_stock',
  'https://www.amazon.com/?tag=yourtag-20',
  null,
  null
),
(
  'offer-ember-mug-amazon-ca',
  'ember-mug',
  'Amazon',
  'CA',
  '',
  135,
  'CAD',
  'in_stock',
  'https://www.amazon.ca/?tag=yourtagca-20',
  null,
  null
),
(
  'offer-weighted-blanket-amazon',
  'weighted-blanket',
  'Amazon',
  'US',
  '',
  58,
  'USD',
  'in_stock',
  'https://www.amazon.com/?tag=yourtag-20',
  null,
  null
),
(
  'offer-weighted-blanket-amazon-ca',
  'weighted-blanket',
  'Amazon',
  'CA',
  '',
  78,
  'CAD',
  'in_stock',
  'https://www.amazon.ca/?tag=yourtagca-20',
  null,
  null
),
(
  'offer-pour-over-kit-amazon',
  'pour-over-kit',
  'Amazon',
  'US',
  '',
  42,
  'USD',
  'in_stock',
  'https://www.amazon.com/?tag=yourtag-20',
  null,
  null
),
(
  'offer-pour-over-kit-amazon-ca',
  'pour-over-kit',
  'Amazon',
  'CA',
  '',
  56,
  'CAD',
  'in_stock',
  'https://www.amazon.ca/?tag=yourtagca-20',
  null,
  null
),
(
  'offer-digital-frame-amazon',
  'digital-frame',
  'Amazon',
  'US',
  '',
  79,
  'USD',
  'in_stock',
  'https://www.amazon.com/?tag=yourtag-20',
  null,
  null
),
(
  'offer-digital-frame-amazon-ca',
  'digital-frame',
  'Amazon',
  'CA',
  '',
  109,
  'CAD',
  'in_stock',
  'https://www.amazon.ca/?tag=yourtagca-20',
  null,
  null
),
(
  'offer-chef-knife-amazon',
  'chef-knife',
  'Amazon',
  'US',
  '',
  68,
  'USD',
  'in_stock',
  'https://www.amazon.com/?tag=yourtag-20',
  null,
  null
),
(
  'offer-chef-knife-amazon-ca',
  'chef-knife',
  'Amazon',
  'CA',
  '',
  89,
  'CAD',
  'in_stock',
  'https://www.amazon.ca/?tag=yourtagca-20',
  null,
  null
),
(
  'offer-book-light-amazon',
  'book-light',
  'Amazon',
  'US',
  '',
  18,
  'USD',
  'in_stock',
  'https://www.amazon.com/?tag=yourtag-20',
  null,
  null
),
(
  'offer-book-light-amazon-ca',
  'book-light',
  'Amazon',
  'CA',
  '',
  24,
  'CAD',
  'in_stock',
  'https://www.amazon.ca/?tag=yourtagca-20',
  null,
  null
),
(
  'offer-desk-plant-kit-amazon',
  'desk-plant-kit',
  'Amazon',
  'US',
  '',
  34,
  'USD',
  'in_stock',
  'https://www.amazon.com/?tag=yourtag-20',
  null,
  null
),
(
  'offer-desk-plant-kit-amazon-ca',
  'desk-plant-kit',
  'Amazon',
  'CA',
  '',
  45,
  'CAD',
  'in_stock',
  'https://www.amazon.ca/?tag=yourtagca-20',
  null,
  null
),
(
  'offer-travel-tumbler-amazon',
  'travel-tumbler',
  'Amazon',
  'US',
  '',
  28,
  'USD',
  'in_stock',
  'https://www.amazon.com/?tag=yourtag-20',
  null,
  null
),
(
  'offer-travel-tumbler-amazon-ca',
  'travel-tumbler',
  'Amazon',
  'CA',
  '',
  38,
  'CAD',
  'in_stock',
  'https://www.amazon.ca/?tag=yourtagca-20',
  null,
  null
),
(
  'offer-silk-pillowcase-amazon',
  'silk-pillowcase',
  'Amazon',
  'US',
  '',
  45,
  'USD',
  'in_stock',
  'https://www.amazon.com/?tag=yourtag-20',
  null,
  null
),
(
  'offer-silk-pillowcase-amazon-ca',
  'silk-pillowcase',
  'Amazon',
  'CA',
  '',
  59,
  'CAD',
  'in_stock',
  'https://www.amazon.ca/?tag=yourtagca-20',
  null,
  null
)
on conflict (id) do update set
  product_id = excluded.product_id,
  merchant = excluded.merchant,
  marketplace = excluded.marketplace,
  external_product_id = excluded.external_product_id,
  price = excluded.price,
  currency = excluded.currency,
  availability = excluded.availability,
  affiliate_url = excluded.affiliate_url,
  commission_rate = excluded.commission_rate,
  last_synced_at = excluded.last_synced_at,
  updated_at = now();
